debian/tests/logind: Skip suspend test if the kernel does not support suspend

diff --git a/debian/tests/logind b/debian/tests/logind
--- a/debian/tests/logind
+++ b/debian/tests/logind
@@ -17,6 +17,60 @@ wait_suspend() {
     echo " * closing lid caused suspend"
 }
 
+test_suspend_on_lid() {
+    if ! grep -q mem /sys/power/state; then
+        echo " * suspend not supported on this testbed, skipping"
+        return
+    fi
+
+    # cleanup handler
+    trap 'rm -f /run/udev/rules.d/70-logindtest-*.rules; udevadm control --reload;
+          kill $KILL_PID;
+          rm /run/systemd/system/systemd-suspend.service;
+          if [ -d /sys/module/scsi_debug ]; then rmmod scsi_debug 2>/dev/null || (sleep 2; rmmod scsi_debug ) || true; fi' \
+                  EXIT INT QUIT TERM PIPE
+
+    # watch what's going on
+    journalctl -f -u systemd-logind.service &
+    KILL_PID="$KILL_PID $!"
+
+    # create fake suspend
+    U=$(systemctl cat systemd-suspend.service | sed '/^ExecStart=/ s_=.*$_=/bin/touch /run/suspend.flag_')
+    echo "$U" > /run/systemd/system/systemd-suspend.service
+    sync
+    systemctl daemon-reload
+
+    # create fake lid switch
+    mkdir -p /run/udev/rules.d
+    echo 'SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="Fake Lid Switch", TAG+="power-switch"' \
+        > /run/udev/rules.d/70-logindtest-lid.rules
+    sync
+    udevadm control --reload
+    evemu-device $(dirname $0)/lidswitch.evemu &
+    KILL_PID="$KILL_PID $!"
+    while [ -z "$O" ]; do
+        sleep 0.1
+        O=$(grep -l '^Fake Lid Switch' /sys/class/input/*/device/name)
+    done
+    O=${O%/device/name}
+    LID_DEV=/dev/${O#/sys/class/}
+
+    # close lid
+    evemu-event $LID_DEV --sync --type 5 --code 0 --value 1
+    # need to wait for 30s suspend inhibition after boot
+    wait_suspend 31
+    # open lid again
+    evemu-event $LID_DEV --sync --type 5 --code 0 --value 0
+
+    echo " * waiting for 30s inhibition time between suspends"
+    sleep 30
+
+    # now closing lid should cause instant suspend
+    evemu-event $LID_DEV --sync --type 5 --code 0 --value 1
+    wait_suspend 2
+    evemu-event $LID_DEV --sync --type 5 --code 0 --value 0
+}
+
 echo " * XDG_SESSION_ID=$XDG_SESSION_ID"
 if grep 'systemd:.*session.*scope' /proc/self/cgroup; then
     echo " * process is in session cgroup"
@@ -37,52 +91,7 @@ LOGINDPID=$(pidof systemd-logind)
 echo " * loginctl succeeds"
 OUT=`loginctl`
 
-# cleanup handler
-trap 'rm -f /run/udev/rules.d/70-logindtest-*.rules; udevadm control --reload;
-      kill $KILL_PID;
-      rm /run/systemd/system/systemd-suspend.service;
-      if [ -d /sys/module/scsi_debug ]; then rmmod scsi_debug 2>/dev/null || (sleep 2; rmmod scsi_debug ) || true; fi' \
-              EXIT INT QUIT TERM PIPE
-
-# watch what's going on
-journalctl -f -u systemd-logind.service &
-KILL_PID="$KILL_PID $!"
-
-# create fake suspend
-U=$(systemctl cat systemd-suspend.service | sed '/^ExecStart=/ s_=.*$_=/bin/touch /run/suspend.flag_')
-echo "$U" > /run/systemd/system/systemd-suspend.service
-sync
-systemctl daemon-reload
-
-# create fake lid switch
-mkdir -p /run/udev/rules.d
-echo 'SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="Fake Lid Switch", TAG+="power-switch"' \
-    > /run/udev/rules.d/70-logindtest-lid.rules
-sync
-udevadm control --reload
-evemu-device $(dirname $0)/lidswitch.evemu &
-KILL_PID="$KILL_PID $!"
-while [ -z "$O" ]; do
-    sleep 0.1
-    O=$(grep -l '^Fake Lid Switch' /sys/class/input/*/device/name)
-done
-O=${O%/device/name}
-LID_DEV=/dev/${O#/sys/class/}
-
-# close lid
-evemu-event $LID_DEV --sync --type 5 --code 0 --value 1
-# need to wait for 30s suspend inhibition after boot
-wait_suspend 31
-# open lid again
-evemu-event $LID_DEV --sync --type 5 --code 0 --value 0
-
-echo " * waiting for 30s inhibition time between suspends"
-sleep 30
-
-# now closing lid should cause instant suspend
-evemu-event $LID_DEV --sync --type 5 --code 0 --value 1
-wait_suspend 2
-evemu-event $LID_DEV --sync --type 5 --code 0 --value 0
+test_suspend_on_lid
 
 P=$(pidof systemd-logind)
 [ "$P" = "$LOGINDPID" ] || { echo "logind crashed" >&2; exit 1; }
