debian/rules: Remove temporary debug output from test failures again, check kernel version
All Debian buildd kernels are recent enough now and tests succeed.

Add a check for kernels older than 3.13 and ignore test failures for those.
Some Ubuntu/PPA buildds still have ancient 3.2 kernels on armhf and powerpc.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -258,15 +258,15 @@ override_dh_strip:
 override_dh_auto_test:
 ifeq (, $(filter nocheck, $(DEB_BUILD_OPTIONS)))
 	# some tests hang under fakeroot, so disable fakeroot
-	# temporarily show kernel version and /etc/hosts, for debugging what
-	# they are failing on
+	# some tests are known to fail under ancient kernels
 	env -u LD_PRELOAD make -C build-deb check || ( \
 		cd build-deb; \
 		for f in test-*.log; do echo "==== $$f ===="; cat $$f; done; \
-		echo "==== /etc/hosts ==="; cat /etc/hosts; \
-		echo "==== kernel version ==="; cat /proc/version; \
-		echo "==== machine id ==="; cat /etc/machine-id; \
-		exit 1)
+		if dpkg --compare-versions $$(uname -r) gt 3.13; then \
+		    exit 1; \
+		else \
+		    echo "Ignoring test failure under too old kernel $$(uname -r)"; \
+		fi)
 endif
 
 %:
