Check during build that systemd and systemd-journald don't link against anything in /usr
This prevents bugs like #771652 and #788913 in the future.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -112,6 +112,12 @@ override_dh_auto_install:
 		--destdir=debian/install/deb
 	dh_auto_install --builddirectory=build-udeb \
 		--destdir=debian/install/udeb
+	echo "Checking that executables don't link to libraries in /usr..."
+	set -e; for e in debian/install/deb/lib/systemd/systemd debian/install/deb/lib/systemd/systemd-journald; do \
+	    OUT=`ldd $$e | grep -v libfakeroot`; if echo "$$OUT" | grep -q /usr; then \
+	        echo "ERROR: $$e links to /usr"; echo "$$OUT"; exit 1; \
+	    fi; \
+	done
 
 override_dh_auto_clean:
 	dh_auto_clean --builddirectory=build-deb
