Small comment tweaks and indentation fixes

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -100,6 +100,7 @@ if dpkg --compare-versions "$2" lt "40-1"; then
     fi
 fi
 
+# Create /etc/machine-id
 systemd-machine-id-setup
 
 if ! getent group systemd-journal >/dev/null; then
@@ -118,21 +119,22 @@ if ! getent passwd systemd-resolve >/dev/null; then
     adduser --system --group --no-create-home --home /run/systemd/resolve systemd-resolve
 fi
 
-# initial update of the Message Catalogs database
+# Initial update of the Message Catalogs database
 _update_catalog
+
+# Make systemd-detect-virt utility usable for non-root users
+setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
 
 # We don’t ship /var/log/journal currently, so only run the following fix for
 # systems where the administrator has explicitly enabled persistent logging by
 # creating /var/log/journal.
 if [ -d /var/log/journal ]; then
-        # Grant read access to /var/log/journal for members of the adm group
-        # via a filesystem ACL. This makes them able to read the journal.
-        # Failure is ignored since there might be file systems mounted without
-        # ACL support.
-        setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal || true
+    # Grant read access to /var/log/journal for members of the adm group
+    # via a filesystem ACL. This makes them able to read the journal.
+    # Failure is ignored since there might be file systems mounted without
+    # ACL support.
+    setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal || true
 fi
-
-setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
 
 # Re-run systemctl enable for any service that was enabled when preinst was run.
 if dpkg --compare-versions "$2" ge "204"; then
