Cleanup hwclock-save.service symlinks when upgrading from the jessie version

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -168,4 +168,11 @@ if dpkg --compare-versions "$2" lt-nl "219-4" && \
     fi
 fi
 
+# Cleanup hwclock-save.service, which was shipped in jessie.
+if dpkg --compare-versions "$2" lt-nl "219-8"; then
+   for t in reboot halt poweroff ; do
+       rm -f /etc/systemd/system/${t}.target.wants/hwclock-save.service
+       rmdir --ignore-fail-on-non-empty /etc/systemd/system/${t}.target.wants 2> /dev/null || true
+   done
+fi
 #DEBHELPER#
